import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";
import Home from "./page";
import About from "./about/page";
import Skills from "./skills/page";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <Navbar />
          <Home />
          <div id="about">
            <About />
          </div>
          <div id="skills">
            <Skills />
          </div>

          <Footer />
        </div>
      </body>
    </html>
  );
}
